site_name: Minimal Devops
site_url: https://MinimalDevops.github.io/mkdocs/
theme:
  name: material
  include_search_page: true
  favicon: images/MinimalDevopsLogo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    #- navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow     # or toc.integrate
    - header.autohide
    - announce.dismiss
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: lime 
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: deep orange
  use_directory_urls: True


plugins:
  - meta-manager:
      merge_entries: ['tags']
  - tags:
      tags_file: tags.md
  - blog
  - macros:
      include_yaml:
        - docs/assets/yaml/macro1.yml
  - mkdocs-pdf
  - search
  - obsidian-interactive-graph
  - ezlinks:
      wikilinks: true
      warn_ambiguities: true



extra:
  pdf: "true"
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MinimalDevops/shared-for-you
    - icon: fontawesome/brands/medium
      link: https://medium.com/@minimaldevops
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/minimal-devops

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/obsidian_tags.js
  - assets/javascripts/interactive_graph.js

extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/MinimalDevops"  target="_blank" rel="noopener">Minimal Devops</a>

nav:
  - Home: index.md
  - AWS:
      - AWS/index.md
      - 'Table of Contents':
        - 'Networking':
          - 'VPC Endpoint': AWS/Networking/AWSNetworkingVpcEndpoint.md
        - 'Database':  
          - 'Cost Optimization': AWS/Database/AWSDatabaseCostSaving.md
        - 'Services':
          - 'Eventbridge' : AWS/Services/AWSServicesEventbridge.md
  #- Azure:
  #- GCP:
  - Databases:
      - Databases/index.md
      - 'Table of Contents':
        - 'Sql': 
          - 'Indexing': Databases/Sql/DatabasesSqlIndexing.md
          - 'Tools': Databases/Sql/DatabasesSqlTools.md
  - System Design:
      - System Design/index.md
      - 'Table of Contents':
        - 'Architectures':
          - 'Event Driven Architecture': System Design/Architecture/SystemDesignEventDrivenAchitecture.md
  - Kubernetes:
      - Kubernetes/index.md
      - 'Table of Contents':
        - 'Deployment Tools':
          - 'Kluctl': Kubernetes/Deployment Tools/KubernetesDeploymentToolsKluctl.md
        - 'Debug Tools':
          - 'Kubeshark': Kubernetes/Debug Tools/KubernetesDebugToolsKubeshark.md
  #- Containers:
  #- Git:
    # Add about readme, doc as code
  - Coding: 
      - Coding/index.md
      - 'Table of Contents':
        - 'Command Line Tools': 
          - 'JQ': Coding/Command Line Tools/CodingCommandLineToolsJq.md
  - Data Engineering: 
      - Data Engineering/index.md
      - 'Table of Contents':
        - 'Data Lake': 
          - 'Apache Hudi': Data Engineering/Data Lake/DataEngineeringDataLakeApacheHudi.md
  #- Security:
  #- Monitoring:
  #- InfraAsCode:
    #Add Diagram as code
  #- Vscode:
    #TODO: #Add about extensions
  - 'Tags': tags.md
  - Blog:
    - blog/index.md

